Models/DBModels.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTrips.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel1 : DbContext
    {
        public DBModel1()
            : base("name=DBModel1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Trip> Trips { get; set; }
    }
}

Models/DBModels.Designer.cs
// T4 code generation is enabled for model 'E:\Dot.Net\Workspace\MyTrips\Models\DBModels.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Models/DBModels.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Models/Trip.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTrips.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Destination { get; set; }
        public Nullable<int> Year { get; set; }
        public string Month { get; set; }
    }
}

Controllers/TripController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using MyTrips.Models;
namespace MyTrips.Controllers
{
    public class TripController : Controller
    {
        // GET: Trip
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetData()
        {
            using(DBModel1 db = new DBModel1())
            {
                List<Trip> tripList = db.Trips.ToList<Trip>();
                return Json(new {data = tripList}, JsonRequestBehavior.AllowGet); 

            }
        }
        [HttpGet]
        public ActionResult AddorEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new Trip());
            }
            else
            {
                using (DBModel1 db = new DBModel1())
                {
                    return View(db.Trips.Where(x => x.Id==id).FirstOrDefault<Trip>());
                }
            }
        }
        
        [HttpPost]
        public ActionResult AddorEdit(Trip trp)
        {
            using (DBModel1 db = new DBModel1())
            {
                if(trp.Id ==0)
                {
                    db.Trips.Add(trp);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);

                }
                else
                {
                    db.Entry(trp).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);

                }
            }
                
        }
        [HttpPost]
        public ActionResult Delete(int id )
        {
            using (DBModel1 db = new DBModel1())
            {
                Trip trp = db.Trips.Where(x => x.Id == id).FirstOrDefault<Trip>();
                db.Trips.Remove(trp);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);

            }

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
</head>
<body>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> ASP.NET CRUD Operations using data table plugin</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Trip/AddorEdit.cshtml
@model MyTrips.Models.Trip
@{
    Layout = null;
}

@using (Html.BeginForm("AddorEdit","Trip",FormMethod.Post, new { onSubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.Id)
<div class="form-group">
    @Html.LabelFor(model => model.Name, new { @class = "control-label" })
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @Class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Name)
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Destination, new { @class = "control-label" })
    @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @Class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Destination)
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Year, new { @class = "control-label" })
    @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @Class = "form-control" } })

</div>
<div class="form-group">
    @Html.LabelFor(model => model.Month, new { @class = "control-label" })
    @Html.EditorFor(model => model.Month, new { htmlAttributes = new { @Class = "form-control" } })

</div>
<div class="form-group">
    <input type="submit" value="Submit" class="btn btn-primary" />
    <input type="reset" value="Reset" class="btn btn-primary" />
</div>

}

Views/Trip/Index.cshtml
@{
    ViewBag.Title = "Trip List";
}

<h2>Trip CRUD Operations</h2>

<a class="btn  btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddorEdit","Trip")')"><i class="fa fa-plus"></i> Add New</a>
<table id="tripTable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Destination</th>
            <th>Year</th>
            <th>Month</th>
            <th></th>
        </tr>
    </thead>
</table>

<link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
@section scripts{
    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script>
        var Popup, dataTable;
        $(document).ready(function () {
            dataTable =  $("#tripTable").DataTable({
                "ajax": {
                    "url": "/Trip/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "Name" },
                    { "data": "Destination" },
                    { "data": "Year" },
                    { "data": "Month" },
                    {
                        "data": "Id", "render": function (data) {
                            return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddorEdit","Trip")/" + data + "')><i class='fa fa - pencil'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left: 5px' onclick=Delete("+data+")><i class='fa fa - trash'></i> Delete</a>"
                        },
                        "orderable": false,
                        "searchable" : false,
                        "width":"150px"
                    }
                ],
                "language": {
                    "emptyTable" : "No data found, Please click on <b> Add New </b> Button"
                }
            });
        });
        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title :'Fill Trip Details',
                        height: 500,
                        width: 700,
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }

                    });
                });
        }
        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {

                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            });
                        }
                    }
                });

            }
            return false;
        }
        function Delete(id) {
            if (confirm('Are You Sure To Delete?')) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Trip")/' + id,
                    success: function (data) {
                        if (data.success) {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })
                            }
                    }
                    });
            }

        }
    </script>
}